name: Build Test
on: [push, pull_request]

jobs:
  build-test:
    name: Build Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"
      - name: Install dependencies NUI
        run: npm install
      - name: Build Bundles
        run: npm build
